title: Koenraad Van Doorslaer, PhD
markdown: kramdown
navigation:
 - text: Home
   url: /
 - text: People
   url: /people
 - text: Opportunities
   url: /opportunities
 - text: Projects
   url: /projects
 - text: Publications
   url: /resume
 - text: Media
   url: /media
 - text: Animal PV Reference Center
   url: /Ref


gem:
    - jekyll-redirect-from
    - jekyll-paginate

